/**
 * Created by jiangyukun on 2017/4/11.
 */
import './boostrap/bootstrap.less'

import './antd/style/index.less'
import './antd/radio/style/index.less'
import './antd/button/style/index.less'
import './antd/modal/style/index.less'
import './antd/notification/style/index.less'
import './antd/date-picker/style/index.less'
import './antd/menu/style/index.less'
import './antd/upload/style/index.less'
import './antd/tooltip/style/index.less'
import './antd/checkbox/style/index.less'

import './variables.scss'
import './common.scss'
import './reset.scss'
import './svg.scss'
import './app.scss'
import './components/form.scss'
import './components/tag.scss'
import './components/button.scss'
import './components/select1.scss'
import './components/query-filter.scss'
import './components/query-filter-select1.scss'
import './components/paginate-list.scss'
import './components/flex-list.scss'
import './components/spinner.scss'
import './components/upload.scss'
import './components/rich-text.scss'
import './pages/pages.scss'
